spring:
  application:
    name: auth-service
  main:
    banner-mode: "off"
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus

