spring:
  application:
    name: auth-service
server:
  port: 8083
  servlet:
    context-path: /api/auth
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus

