version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    driver: bridge

volumes:
  redis-inmemory-storage:

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - web-app-net
    volumes:
      - redis-inmemory-storage:/data

##End Of Scripts