spring:
  application:
    name: first-service
  main:
    banner-mode: "off"
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus