spring:
  application:
    name: first-service
  main:
    banner-mode: "off"
server:
  port: 8081
  servlet:
    context-path: /api/employee
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus
app:
  home:
    #upload: /home/${USER}/Downloads
    upload: /Users/${USER}/Downloads
    #logs: /home/${USER}/Logs
    logs: /Users/${USER}/Logs