spring:
  application:
    name: first-service
  main:
    banner-mode: "off"
server:
  port: 8081
  servlet:
    context-path: /api/employee
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus
app:
  home:
    #logs: /Users/${USER}/Logs
    logs: /Users/Logs
#Eureka-Config:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:801/eureka