spring:
  application:
    name: api-gateway
server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus,gateway
#Spring-Redis-Config:
redis:
  host: localhost
  port: 6379
#Eureka-Config:
app.eureka.service.host: localhost
app.eureka.service.port: 801
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.service.host}:${app.eureka.service.port}/eureka