spring:
  application:
    name: api-gateway
server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus,gateway
#Spring-Redis-Config:
redis:
  host: localhost
  port: 6379
#Eureka-Config:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:801/eureka