spring:
  application:
    name: second-service
server:
  port: 8082
  servlet:
    context-path: /api/consumer
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus